version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: postgres
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - postgres

volumes:
  db_data:

networks:
  app-network:
    driver: bridge